import pandas as pd

# df = pd.read_csv("blood_pressure.csv")

df_random = pd.read_csv("random.csv")
df_util = pd.read_csv("util_only.csv")
df_compat = pd.read_csv("compat_only.csv")
df_lucene = pd.read_csv("lucene.csv")
df_evpi = pd.read_csv("evpi.csv")

from scipy import stats

# print("random: mrr & p_1", stats.wilcoxon(df_random['mrr'], df_random['p_1']))
# print("random: mrr & p_3", stats.wilcoxon(df_random['mrr'], df_random['p_3']))
# print("random: mrr & p_5", stats.wilcoxon(df_random['mrr'], df_random['p_5']))
# print("======================================================================")
# print("compat: mrr & p_1", stats.wilcoxon(df_compat['mrr'], df_compat['p_1']))
# print("compat: mrr & p_3", stats.wilcoxon(df_compat['mrr'], df_compat['p_3']))
# print("compat: mrr & p_5", stats.wilcoxon(df_compat['mrr'], df_compat['p_5']))
# print("======================================================================")
# print("util: mrr & p_1", stats.wilcoxon(df_util['mrr'], df_util['p_1']))
# print("util: mrr & p_3", stats.wilcoxon(df_util['mrr'], df_util['p_3']))
# print("util: mrr & p_5", stats.wilcoxon(df_util['mrr'], df_util['p_5']))
# print("======================================================================")
# print("lucene: mrr & p_1", stats.wilcoxon(df_lucene['mrr'], df_lucene['p_1']))
# print("lucene: mrr & p_3", stats.wilcoxon(df_lucene['mrr'], df_lucene['p_3']))
# print("lucene: mrr & p_5", stats.wilcoxon(df_lucene['mrr'], df_lucene['p_5']))
# print("======================================================================")
# print("evpi: mrr & p_1", stats.wilcoxon(df_evpi['mrr'], df_evpi['p_1']))
# print("evpi: mrr & p_3", stats.wilcoxon(df_evpi['mrr'], df_evpi['p_3']))
# print("evpi: mrr & p_5", stats.wilcoxon(df_evpi['mrr'], df_evpi['p_5']))
# print("======================================================================")
#
#
# print("mrr: random and util_only", stats.wilcoxon(df_random['mrr'], df_util['mrr']))
# print("mrr: random and compat_only", stats.wilcoxon(df_random['mrr'], df_compat['mrr']))
# print("mrr: random and lucene", stats.wilcoxon(df_random['mrr'], df_lucene['mrr']))
# print("mrr: random and evpi", stats.wilcoxon(df_random['mrr'], df_evpi['mrr']))
# print("mrr: util_only and compat_only", stats.wilcoxon(df_util['mrr'], df_compat['mrr']))
# print("mrr: util_only and lucene", stats.wilcoxon(df_util['mrr'], df_lucene['mrr']))
# print("mrr: util_only and evpi", stats.wilcoxon(df_util['mrr'], df_evpi['mrr']))
# print("mrr: compat_only and lucene", stats.wilcoxon(df_compat['mrr'], df_lucene['mrr']))
# print("mrr: compat_only and evpi", stats.wilcoxon(df_compat['mrr'], df_evpi['mrr']))
# print("mrr: lucene and evpi", stats.wilcoxon(df_lucene['mrr'], df_evpi['mrr']))
#
#
# print("mrr: random and util_only", stats.wilcoxon(df_random['mrr'], df_util['mrr']))
# print("mrr: random and compat_only", stats.wilcoxon(df_random['mrr'], df_compat['mrr']))
# print("mrr: random and lucene", stats.wilcoxon(df_random['mrr'], df_lucene['mrr']))
# print("mrr: random and evpi", stats.wilcoxon(df_random['mrr'], df_evpi['mrr']))
# print("mrr: util_only and compat_only", stats.wilcoxon(df_util['mrr'], df_compat['mrr']))
# print("mrr: util_only and lucene", stats.wilcoxon(df_util['mrr'], df_lucene['mrr']))
# print("mrr: util_only and evpi", stats.wilcoxon(df_util['mrr'], df_evpi['mrr']))
# print("mrr: compat_only and lucene", stats.wilcoxon(df_compat['mrr'], df_lucene['mrr']))
# print("mrr: compat_only and evpi", stats.wilcoxon(df_compat['mrr'], df_evpi['mrr']))
# print("mrr: lucene and evpi", stats.wilcoxon(df_lucene['mrr'], df_evpi['mrr']))
#
# print("===========================================================================")
#
# print("p@1: random and util_only", stats.wilcoxon(df_random['p_1'], df_util['p_1']))
# print("p@1: random and compat_only", stats.wilcoxon(df_random['p_1'], df_compat['p_1']))
# print("p@1: random and lucene", stats.wilcoxon(df_random['p_1'], df_lucene['p_1']))
# print("p@1: random and evpi", stats.wilcoxon(df_random['p_1'], df_evpi['p_1']))
# print("p@1: util_only and compat_only", stats.wilcoxon(df_util['p_1'], df_compat['p_1']))
# print("p@1: util_only and lucene", stats.wilcoxon(df_util['p_1'], df_lucene['p_1']))
# print("p@1: util_only and evpi", stats.wilcoxon(df_util['p_1'], df_evpi['p_1']))
# print("p@1: compat_only and lucene", stats.wilcoxon(df_compat['p_1'], df_lucene['p_1']))
# print("p@1: compat_only and evpi", stats.wilcoxon(df_compat['p_1'], df_evpi['p_1']))
# print("p@1: lucene and evpi", stats.wilcoxon(df_lucene['p_1'], df_evpi['p_1']))
#
# print("===========================================================================")
#
# print("p@3: random and util_only", stats.wilcoxon(df_random['p_3'], df_util['p_3']))
# print("p@3: random and compat_only", stats.wilcoxon(df_random['p_3'], df_compat['p_3']))
# print("p@3: random and lucene", stats.wilcoxon(df_random['p_3'], df_lucene['p_3']))
# print("p@3: random and evpi", stats.wilcoxon(df_random['p_3'], df_evpi['p_3']))
# print("p@3: util_only and compat_only", stats.wilcoxon(df_util['p_3'], df_compat['p_3']))
# print("p@3: util_only and lucene", stats.wilcoxon(df_util['p_3'], df_lucene['p_3']))
# print("p@3: util_only and evpi", stats.wilcoxon(df_util['p_3'], df_evpi['p_3']))
# print("p@3: compat_only and lucene", stats.wilcoxon(df_compat['p_3'], df_lucene['p_3']))
# print("p@3: compat_only and evpi", stats.wilcoxon(df_compat['p_3'], df_evpi['p_3']))
# print("p@3: lucene and evpi", stats.wilcoxon(df_lucene['p_3'], df_evpi['p_3']))
#
# print("===========================================================================")
#
# print("p@5: random and util_only", stats.wilcoxon(df_random['p_5'], df_util['p_5']))
# print("p@5: random and compat_only", stats.wilcoxon(df_random['p_5'], df_compat['p_5']))
# print("p@5: random and lucene", stats.wilcoxon(df_random['p_5'], df_lucene['p_5']))
# print("p@5: random and evpi", stats.wilcoxon(df_random['p_5'], df_evpi['p_5']))
# print("p@5: util_only and compat_only", stats.wilcoxon(df_util['p_5'], df_compat['p_5']))
# print("p@5: util_only and lucene", stats.wilcoxon(df_util['p_5'], df_lucene['p_5']))
# print("p@5: util_only and evpi", stats.wilcoxon(df_util['p_5'], df_evpi['p_5']))
# print("p@5: compat_only and lucene", stats.wilcoxon(df_compat['p_5'], df_lucene['p_5']))
# print("p@5: compat_only and evpi", stats.wilcoxon(df_compat['p_5'], df_evpi['p_3']))
# print("p@5: lucene and evpi", stats.wilcoxon(df_lucene['p_5'], df_evpi['p_5']))
#
# print("==============================================================================")

print("mrr: evpi and random", stats.wilcoxon(df_evpi['mrr'], df_random['mrr'])[1].__round__(2))
print("mrr: evpi and util_only", stats.wilcoxon(df_evpi['mrr'], df_util['mrr'])[1].__round__(2))
print("mrr: evpi and compat_only", stats.wilcoxon(df_evpi['mrr'], df_compat['mrr'])[1].__round__(2))
print("mrr: evpi and lucene", stats.wilcoxon(df_evpi['mrr'], df_lucene['mrr'])[1].__round__(2))
print("==============================================================================")
print("p@1: evpi and random", stats.wilcoxon(df_evpi['p_1'], df_random['p_1'])[1].__round__(2))
print("p@1: evpi and util_only", stats.wilcoxon(df_evpi['p_1'], df_util['p_1'])[1].__round__(2))
print("p@1: evpi and compat_only", stats.wilcoxon(df_evpi['p_1'], df_compat['p_1'])[1].__round__(2))
print("p@1: evpi and lucene", stats.wilcoxon(df_evpi['p_1'], df_lucene['p_1'])[1].__round__(2))
print("==============================================================================")
print("p@3: evpi and random", stats.wilcoxon(df_evpi['p_3'], df_random['p_3'])[1].__round__(2))
print("p@3: evpi and util_only", stats.wilcoxon(df_evpi['p_3'], df_util['p_3'])[1].__round__(2))
print("p@3: evpi and compat_only", stats.wilcoxon(df_evpi['p_3'], df_compat['p_3'])[1].__round__(2))
print("p@3: evpi and lucene", stats.wilcoxon(df_evpi['p_3'], df_lucene['p_3'])[1].__round__(2))
print("==============================================================================")
print("p@5: evpi and random", stats.wilcoxon(df_evpi['p_5'], df_random['p_5'])[1].__round__(2))
print("p@5: evpi and util_only", stats.wilcoxon(df_evpi['p_5'], df_util['p_5'])[1].__round__(2))
print("p@5: evpi and compat_only", stats.wilcoxon(df_evpi['p_5'], df_compat['p_5'])[1].__round__(2))
print("p@5: evpi and lucene", stats.wilcoxon(df_evpi['p_5'], df_lucene['p_5'])[1].__round__(2))
print("==============================================================================")